In [6]:
import os
import numpy as np
from stl import mesh

import pyvista as pv

from pyvistaqt import BackgroundPlotter


In [2]:

sc = mesh.Mesh.from_file(r'YOUR_DATA_PATH/Spinal Cord.stl')


In [4]:
volume, cog, inertia = sc.get_mass_properties()
xyz = (sc.max_ - sc.min_)
sizel = round(xyz[0] / 10, 2)
sizew = round(xyz[1] / 10, 2)
sizeh = round(xyz[2] / 10, 2)

Your mesh is not closed, the mass methods will not function
            correctly on this mesh.  For more info:
            https://github.com/WoLpH/numpy-stl/issues/69


In [2]:
#读取stl文件
import vtk
def readstl_vtk(filepath):
	# create data mannualy
	# cylinder = vtk.vtkCylinderSource()
	# cylinder.SetHeight(3.0) # 设置柱体的高
	# cylinder.SetRadius(1.0) #	 设置柱体横截面的半径
	# cylinder.SetResolution(6) # 设置柱体横截面的等边多边形的边数
 
	# Read from file
	stlreader = vtk.vtkSTLReader()
	f=stlreader.SetFileName(filepath)
	
	cylinderMapper = vtk.vtkPolyDataMapper() # 渲染多边形几何数据
	cylinderMapper.SetInputConnection(stlreader.GetOutputPort()) # VTK可视化管线的输入数据接口 ，对应的可视化管线输出数据的接口为GetOutputPort()；
	cylinderActor = vtk.vtkActor()
	cylinderActor.SetMapper(cylinderMapper) # 设置生成几何图元的Mapper。即连接一个Actor到可视化管线的末端(可视化管线的末端就是Mapper)。
	renderer = vtk.vtkRenderer() # 负责管理场景的渲染过程
	renderer.AddActor(cylinderActor)
	renderer.SetBackground(0.1, 0.2, 0.4)
	renWin = vtk.vtkRenderWindow() # 将操作系统与VTK渲染引擎连接到一起。
	renWin.AddRenderer(renderer)
	renWin.SetSize(300, 300)
	iren = vtk.vtkRenderWindowInteractor() # 提供平台独立的响应鼠标、键盘和时钟事件的交互机制
	iren.SetRenderWindow(renWin)
 
	# 交互器样式的一种，该样式下，用户是通过控制相机对物体作旋转、放大、缩小等操作
	style = vtk.vtkInteractorStyleTrackballCamera()
 
	iren.SetInteractorStyle(style)
	iren.Initialize()
 
	iren.Start()
 
	# Clean up
	# del cylinder
	del stlreader
	del cylinderMapper
	del cylinderActor
	del renderer
	del renWin
	del iren
 
readstl_vtk(r'YOUR_DATA_PATH/Spinal Cord.stl')

## 导入标记数据并展示

In [2]:
import pyvista as pv
from pyvistaqt import BackgroundPlotter

def readstl_pv(filepath):
    meshes = pv.read(stl_files)
    plotter = BackgroundPlotter()
    for mesh in meshes:
        plotter.add_mesh(mesh)
    plotter.show()



 
stl_files = [r'YOUR_DATA_PATH/Spinal Cord.stl', r'YOUR_DATA_PATH/T11.stl']


readstl_pv(stl_files)

In [4]:




def readstl_pv(filepath):

    meshes = pv.read(stl_files)

    plotter = BackgroundPlotter()

    for mesh in meshes:

        plotter.add_mesh(mesh)

    plotter.show()



stl_files = [r'YOUR_DATA_PATH/Spinal Cord.stl', r'YOUR_DATA_PATH/T11.stl']


readstl_pv(stl_files)

In [1]:
import pandas as pd
IF_L_Tbl = pd.DataFrame.from_dict(pd.read_json(r'YOUR_DATA_PATH\IF_L.mrk.json')['markups'][0]['controlPoints'])
IF_R_Tbl = pd.DataFrame.from_dict(pd.read_json(r'YOUR_DATA_PATH\IF_R.mrk.json')['markups'][0]['controlPoints'])
DREP_L_Tbl = pd.DataFrame.from_dict(pd.read_json(r'YOUR_DATA_PATH\DREP_L.mrk.json')['markups'][0]['controlPoints'])
DREP_R_Tbl = pd.DataFrame.from_dict(pd.read_json(r'YOUR_DATA_PATH\DREP_R.mrk.json')['markups'][0]['controlPoints'])

In [2]:
IF_L_Tbl

id     label description          associatedNodeID  \
0  1  IF_L_T11              vtkMRMLScalarVolumeNode9   
1  2  IF_L_T12              vtkMRMLScalarVolumeNode9   
2  3   IF_L_L1              vtkMRMLScalarVolumeNode9   
3  4   IF-L_L2              vtkMRMLScalarVolumeNode9   

                                            position  \
0  [-15.748205410585879, 47.50696168142474, -25.5...   
1  [-15.756392562144113, 45.479402051193176, -55....   
2  [-15.776938215929848, 40.39159123812232, -89.3...   
3  [-15.802593332852696, 34.03860915462013, -118....   

                                         orientation  selected  locked  \
0  [-1.0, -0.0, -0.0, -0.0, -1.0, -0.0, 0.0, 0.0,...      True   False   
1  [-1.0, -0.0, -0.0, -0.0, -1.0, -0.0, 0.0, 0.0,...      True   False   
2  [-1.0, -0.0, -0.0, -0.0, -1.0, -0.0, 0.0, 0.0,...      True   False   
3  [-1.0, -0.0, -0.0, -0.0, -1.0, -0.0, 0.0, 0.0,...      True   False   

   visibility positionStatus  
0        True        defined  
1        True        defined  
2        True        defined  
3        True        defined

In [66]:
a= DREP_L_Tbl['position'][0][2]

In [83]:
DREP_L_Tbl

id     label description associatedNodeID  \
0  1  DREP_L-1                                

                                            position  \
0  [-2.249308109283447, 52.77119827270508, -8.776...   

                                         orientation  selected  locked  \
0  [-1.0, -0.0, -0.0, -0.0, -1.0, -0.0, 0.0, 0.0,...      True   False   

   visibility positionStatus  
0        True        defined

In [13]:
if_L = [np.array(i) for i in IF_L_Tbl['position']]
if_L

[array([-15.74820541,  47.50696168, -25.55525605]),
 array([-15.75639256,  45.47940205, -55.66134346]),
 array([-15.77693822,  40.39159124, -89.35914824]),
 array([ -15.80259333,   34.03860915, -118.54428739])]

In [12]:
# Spinal Cord Segmentation
import dicom2nifti

dicom2nifti.convert_directory(r"YOUR_DATA_PATH\t2_de3d_we_sag_p2_iso_0005", r"YOUR_DATA_PATH", compression=True, reorient=True)


In [1]:
# Spinal Cord Segmentation
import dicom2nifti

dicom2nifti.convert_directory(r"YOUR_DATA_PATH\t2_space_cor_iso_myelo_ZOOMit_0009", r"YOUR_DATA_PATH", compression=True, reorient=True)


In [13]:
dicom2nifti.convert_directory(r"YOUR_DATA_PATH\t2_tse_sag_p2_448_0002", r"YOUR_DATA_PATH", compression=True, reorient=True)


In [2]:
# Spinal Cord Segmentation
import dicom2nifti

dicom2nifti.convert_directory(r"YOUR_DATA_PATH\t2_tse_sag_p2_448_0003", r"YOUR_DATA_PATH", compression=True, reorient=True)


In [ ]:
pv.set_jupyter_backend('trame')  

In [3]:
import pyvista as pv

# # Load the JSON file
# json_file = r"YOUR_DATA_PATH\IF_L.mrk.json"
# if_L = pd.read_json(json_file)['markups'][0]['controlPoints']

# 坐标矩阵
# vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 0.5, 0], [0, 0.5, 0]])
# poly_data = pv.PolyData(vertices)

# 随机点云
# nodes = np.random.rand(100, 3)
# mesh = pv.PolyData(nodes)

# if_L

if_L = np.array([np.array(i) for i in IF_L_Tbl['position']])
poly_data = pv.PolyData(if_L)

# Visualize the fiducial points
plotter = pv.Plotter()
plotter.add_mesh(poly_data, color='red', point_size=10, render_points_as_spheres=True)

plotter.show()


Widget(value="<iframe src='http://localhost:55463/index.html?ui=P_0x20833ee3be0_0&reconnect=auto' style='width…

In [18]:
line = pv.Line(center, interp1)

In [32]:
if_L

array([[ -15.74820541,   47.50696168,  -25.55525605],
       [ -15.75639256,   45.47940205,  -55.66134346],
       [ -15.77693822,   40.39159124,  -89.35914824],
       [ -15.80259333,   34.03860915, -118.54428739]])

In [7]:
list(IF_L_Tbl['label'])

['IF_L_T11', 'IF_L_T12', 'IF_L_L1', 'IF-L_L2']

In [7]:




# if_L
if_L = np.array([np.array(i) for i in IF_L_Tbl['position']])
DREP_L = np.array([np.array(i) for i in DREP_L_Tbl['position']])


# poly_data = pv.PolyData(if_L)

# Visualize the fiducial points
#plotter = pv.Plotter()
plotter = BackgroundPlotter()
# plotter.add_mesh(poly_data, color='red', point_size=10, render_points_as_spheres=True) # no need if use add_point_labels


plotter.add_point_labels(if_L, list(IF_L_Tbl['label']), font_size=24, point_color='red', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(DREP_L, list(DREP_L_Tbl['label']), font_size=24, point_color='green', point_size=20, render_points_as_spheres=True, always_visible=True)

#import spinal cord and vertebrae
stl_files = [r'YOUR_DATA_PATH/Spinal Cord.stl', r'YOUR_DATA_PATH/T11.stl']

meshes = pv.read(stl_files)

#plotter = BackgroundPlotter()

for mesh in meshes:

        plotter.add_mesh(mesh)

plotter.show()



In [35]:
if_L

array([[ -15.74820541,   47.50696168,  -25.55525605],
       [ -15.75639256,   45.47940205,  -55.66134346],
       [ -15.77693822,   40.39159124,  -89.35914824],
       [ -15.80259333,   34.03860915, -118.54428739]])

In [12]:
 import pyvista as pv

# Create a PyVista PolyData object
poly_data = pv.PolyData()
poly_data.points = [[0, 0, 0], [1, 0, 0], [0, 1, 0]]
poly_data.faces = [[0, 1, 2]]

# Create a plotter
plotter = pv.Plotter()

# Add the PolyData to the plotter
plotter.add_mesh(poly_data)

# Add string labels to the points
labels = ["Point 1", "Point 2", "Point 3"]
point_ids = [0, 1, 2]
plotter.add_point_labels(poly_data.points, labels)

# Display the interactive window
plotter.show()


C:\ProgramData\anaconda3\lib\site-packages\pyvista\utilities\helpers.py:507: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(


Widget(value="<iframe src='http://localhost:49979/index.html?ui=P_0x23a84ac0100_5&reconnect=auto' style='width…

## 切面识别中心

In [9]:
# 在DREP高度切片
sliced_mesh = meshes[0].slice(normal='z', origin=DREP_L_Tbl['position'][0])


In [172]:
center[2]

-8.776601791381836

In [197]:
center

array([-1.45599413, 49.35988808, -8.77660179])

In [198]:
cart2polTransform(np.array([20,0,center[2]]),center,direction= 'pol2cart')

array([ 18.54400587,  49.35988808, -17.55320358])

In [ ]:
bection= 'pol2cart')))
#plotter.add_mesh(pv.Line(center,cart2polTransform(np.array([20,math.pi/2,0]),center,direction= 'pol2cart')))
plotter.add_point_labels(if_L[2], [IF_L_Tbl['label'][2]], font_size=24, point_color='red', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(DREP_L, list(DREP_L_Tbl['label']), font_size=24, point_color='green', point_size=20, render_points_as_spheres=True, always_visible=True)


plotter.show()

In [ ]:
def polyline_from_points(points):
    poly = pv.PolyData()
    poly.points = points
    the_cell = np.arange(0, len(points), dtype=np.int_)
    the_cell = np.insert(the_cell, 0, len(points))
    poly.lines = the_cell
    return poly


polyline = polyline_from_points(points)
polyline["scalars"] = np.arange(polyline.n_points)
tube = polyline.tube(radius=0.1)
tube.plot(smooth_shading=True)

In [216]:
[IF_L_Tbl['label'][2]]

['IF_L_L1']

In [217]:
list(DREP_L_Tbl['label'])

['DREP_L-1']

In [154]:
if_L[2]

array([-15.77693822,  40.39159124, -89.35914824])

In [155]:
DREP_L

array([[-2.24930811, 52.77119827, -8.77660179]])

In [152]:
interp_list

[array([ -1.16945849,  53.24217374, -14.33401879]),
 array([ -0.34762466,  54.20802887, -17.11272729]),
 array([  0.49558764,  54.30568402, -19.89143578]),
 array([  1.32015382,  54.13164767, -22.67014428]),
 array([  2.00672002,  53.65945757, -25.44885278]),
 array([  2.66242378,  53.13331622, -28.22756128]),
 array([  3.18344251,  52.47047543, -31.00626978]),
 array([  3.59876304,  51.73676754, -33.78497827]),
 array([  3.82537361,  50.9270831 , -36.56368677]),
 array([  4.00108817,  50.11434036, -39.34239527]),
 array([  3.13298356,  49.29700846, -42.12110377]),
 array([  3.25901023,  48.57582112, -44.89981227]),
 array([  3.1982013 ,  47.83885853, -47.67852077]),
 array([  2.96302419,  47.13211206, -50.45722926]),
 array([  2.57738686,  46.49238975, -53.23593776]),
 array([  2.05912299,  45.95742665, -56.01464626]),
 array([  1.50698218,  45.46713025, -58.79335476]),
 array([  0.80309526,  45.21990185, -61.57206326]),
 array([  0.1086037 ,  45.05273195, -64.35077175]),
 array([ -0.

In [10]:
# Calculate the center of the sliced mesh
center = np.array(sliced_mesh.center)
interp1 = np.array([-5, 54, center[2]])

In [11]:
sliced_mesh

PolyData (0x2084f68d5a0)
  N Cells:    119
  N Points:   119
  N Strips:   0
  X Bounds:   -6.103e+00, 3.191e+00
  Y Bounds:   4.592e+01, 5.280e+01
  Z Bounds:   -8.777e+00, -8.777e+00
  N Arrays:   0

In [13]:
center

[-1.4559941291809082, 49.35988807678223, -8.776601791381836]

In [243]:

# Compute the intersection between the line and the slice contour
line = pv.Line(center, interp1)
#intersection = sliced_mesh.intersect_with_line(line)
intersection, s1_split, l_split = cube.intersection(line)
# Calculate the distance between the center and the intersection point
#distance = np.linalg.norm(center - intersection)

In [17]:
d = np.sqrt(np.sum((center-interp1)**2))

5.838717005677526

In [150]:
center

[-1.4559941291809082, 49.35988807678223, -8.776601791381836]

In [151]:
interp1

array([-5.        , 54.        , -8.77660179])

In [208]:
type(contour_on_line)

pyvista.core.pointset.PolyData

In [206]:
# Sample the contour along the line
contour_on_line = sliced_mesh.probe(line)


In [8]:
cube = sliced_mesh.extract_surface().triangulate()

In [232]:
type(cube)

pyvista.core.pointset.PolyData

In [235]:
# Create a plotter
plotter = pv.Plotter()

# Add the PolyData to the plotter
plotter.add_mesh(cube,color='blue')

# Display the interactive window
plotter.show()


Widget(value="<iframe src='http://localhost:52712/index.html?ui=P_0x1a989f5c760_54&reconnect=auto' style='widt…

### 投影后 find closest point

In [218]:
import pyvista as pv


# Sample the contour along the line
contour_on_line = sliced_mesh.probe(line)

# Find the point where the scalar value changes
intersections = contour_on_line.threshold([0.5, 1.0])

# Get the intersection point
intersection_point = intersections.points[0]

# Print the intersection point
print("Intersection Point:", intersection_point)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [11]:
plotter = pv.Plotter()

plotter.add_mesh(sliced_mesh, color = 'red')
plotter.add_point_labels(center, ['O'], point_color = 'yellow', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(interp1, ['interp1'], point_color = 'blue', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(DREP_L, list(DREP_L_Tbl['label']), font_size=24, point_color='green', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(sliced_mesh.points[93], ['X'], point_color = 'blue', point_size=20, render_points_as_spheres=True, always_visible=True)

#plotter.add_mesh(contour_on_line, color = 'blue')
#plotter.add_mesh(line, color = 'red')


plotter.show()

Widget(value="<iframe src='http://localhost:64917/index.html?ui=P_0x1d9befef1c0_0&reconnect=auto' style='width…

In [244]:
# Sample the contour along the line
contour_on_line = cube.probe(line)

# Find the point where the scalar value changes
intersections = contour_on_line.threshold([0.5, 1.0])

In [249]:
intersections

UnstructuredGrid (0x1a96ff48460)
  N Cells:    0
  N Points:   0
  X Bounds:   1.000e+299, -1.000e+299
  Y Bounds:   1.000e+299, -1.000e+299
  Z Bounds:   1.000e+299, -1.000e+299
  N Arrays:   5

In [9]:
# Compute the intersection between the line and the slice contour
line = pv.Line(center, interp1)

In [10]:
# Get the coordinates of the line
line_points = line.points

# Find the closest point on the spline to the line
closest_point = sliced_mesh.find_closest_point(interp1)

In [11]:
line_points

pyvista_ndarray([[-1.4559941, 49.359886 , -8.776602 ],
                 [-5.       , 54.       , -8.776602 ]], dtype=float32)

In [12]:
closest_point

93

In [14]:
sliced_mesh.points[93]

pyvista_ndarray([-4.4840612, 52.605656 , -8.776602 ], dtype=float32)

In [ ]:
import numpy as np

# use one of...
from pykdtree.kdtree import KDTree
# from scipy.spatial import cKDTree as KDTree

import pyvista

sphere = pyvista.Sphere()


tree = KDTree(sphere.points.astype(np.double))

pts = np.array([[0, 0.2, 0.2]])
dist, idx = tree.query(pts)

nearest_pt = sphere.points[idx]
print(f'Nearest point from {pts[0]}')
print(f'...       is point {nearest_pt[0]}')

In [203]:
plotter = pv.Plotter()
plotter.add_mesh(sliced_mesh, color = 'red')
plotter.add_mesh(line, color = 'red')
plotter.add_point_labels(center, ['O'], point_color = 'yellow', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(interp1, ['interp1'], point_color = 'blue', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(DREP_L, list(DREP_L_Tbl['label']), font_size=24, point_color='green', point_size=20, render_points_as_spheres=True, always_visible=True)


plotter.show()

Widget(value="<iframe src='http://localhost:52712/index.html?ui=P_0x1a9484004f0_43&reconnect=auto' style='widt…

In [77]:
# about the contour error
mesh = pv.StructuredGrid(x,y,z).elevation()
contours = mesh.contour()

p = pv.Plotter(notebook=False, border=True)
p.add_mesh(contours, clim=[zmin,zmax], cmap='gist_rainbow')
p.add_axes()
p.add_bounding_box()
p.show_grid()
p.view_xy(negative=False)
p.show()

#
########################################

mesh = pv.StructuredGrid(x,y,z)
mesh['my scalars'] = z.ravel(order='f')


PolyData (0x1a8ae924340)
  N Cells:    65708
  N Points:   32856
  N Strips:   0
  X Bounds:   -3.039e+01, 3.009e+01
  Y Bounds:   2.687e+01, 6.860e+01
  Z Bounds:   -4.205e+01, 8.699e+00
  N Arrays:   0

In [ ]:
import pyvista as pv
import vtk


# Create a vtkPolyData object from the spline PolyData
vtk_spline_polydata = 
vtk_spline_polydata.ShallowCopy(spline_polydata)

# Create a vtkLineSource object for the line
line_source = vtk.vtkLineSource()
line_source.SetPoint1(0.0, 0.0, 0.0)
line_source.SetPoint2(1.0, 1.0, 1.0)
line_source.Update()

# Perform intersection using vtkIntersectionPolyDataFilter
intersection_filter = vtk.vtkIntersectionPolyDataFilter()
intersection_filter.SetInputData(0, vtk_spline_polydata)
intersection_filter.SetInputData(1, line_source.GetOutput())
intersection_filter.Update()

# Get the intersection points
intersection_points = intersection_filter.GetOutput()

# Get the first intersection point
if intersection_points.GetNumberOfPoints() > 0:
    intersection_point = intersection_points.GetPoint(0)
    print("Intersection Point:", intersection_point)
else:
    print("No intersection found.")


## 插值点采样

In [98]:
center

array([-1.45599413, 49.35988808, -8.77660179])

In [235]:
# 参数设定：can
def interpolate_point_sampling(num,origin,entrypoint,endpoint):
    # Parameters：
    # num： the number of sampling points to interpolate(including the enterpoint and endpoint)
    # entrypoint: the 3-D array of enrtypoint()
    #
    # Varaibles:
    # z: the height of the point(polar/cartesian coordinate)
    # a: the angle of the point(polar coordinate relative to the DREP height slice center)
    # d: the radius of the point(polar coordinate relative to the DREP height slice center)
    
    # Coordinate system transform
    etrp_pol = cart2polTransform(entrypoint,origin)
    endp_pol = cart2polTransform(endpoint,origin)
    d,a,z =[],[],[]

    for i in range(num-2):
        
        ai = etrp_pol[1] + ((i+2)/(num-1))*(endp_pol[1] - etrp_pol[1])
        zi = etrp_pol[2] + ((i+2)/(num-1))*(endp_pol[2]-etrp_pol[2])
        print(i,ai)
        #dwmi = get_dwm(ai)
        #di = dwmi + gapSC
        di = etrp_pol[0] + ((i+2)/(num-1))*(endp_pol[0]-etrp_pol[0])
        print(di)
        
        d.append(di)
        a.append(ai)
        z.append(zi)
        
        
        
    return d,a,z

    
    



In [261]:

def interpolate_point_sampling(num,origin,entrypoint,endpoint,gapSC):
    # Parameters：
    # num： the number of sampling points to interpolate(including the enterpoint and endpoint)
    # entrypoint: the 3-D array of enrtypoint()
    #
    # Varaibles:
    # z: the height of the point(polar/cartesian coordinate)
    # a: the angle of the point(polar coordinate relative to the DREP height slice center)
    # d: the radius of the point(polar coordinate relative to the DREP height slice center)
    
    # Coordinate system transform
    etrp_pol = cart2polTransform(entrypoint,origin)
    endp_pol = cart2polTransform(endpoint,origin)
    d,a,z =[],[],[]
    print(etrp_pol,endp_pol)
    ai = etrp_pol[1]
    for i in range(2,num):
        if ai <= math.pi:
            print('yes')
            
            zi = etrp_pol[2] + (i/(num-1))*(endp_pol[2] - etrp_pol[2])
            ai = etrp_pol[1] + (i/(num-1))*(endp_pol[1] - etrp_pol[1])
            dwmi = get_dwm(ai)
            di = dwmi + gapSC
            print(di,ai,zi)
            i0 = i
            di0 = di
            ai0 = ai
            zi0 = zi
        else:
            print('no',di,ai,zi)
            wi = (i-i0)/(num-i0)
            di = (1-wi)*di0+wi*endp_pol[0]
            ai = (1-wi)*ai0+wi*endp_pol[1]
            zi = (1-wi)*zi0+wi*endp_pol[2]
        d.append(di)
        a.append(ai)
        z.append(zi)
        
        
        
    return d,a,z


In [119]:
etrp_pol = cart2polTransform(DREP_L[0],center)
endp_pol = cart2polTransform(if_L[2],center)

In [156]:
etrp_pol

array([3.50233984, 1.79928908, 0.        ])

In [157]:
endp_pol

array([ 16.89733079,  -2.58210472, -80.58254645])

In [127]:
range(29)[-1]

28

In [246]:
for i in zip(d,a,z):
    print(i)

(4.42613231497416, 1.9304471154770748, -5.557416996285752)
(4.888028554675323, 1.996026133054288, -8.336125494428627)
(5.349924794376486, 2.0616051506315016, -11.114833992571503)
(5.811821034077649, 2.127184168208715, -13.89354249071438)
(6.2737172737788125, 2.192763185785928, -16.672250988857254)
(6.735613513479976, 2.2583422033631417, -19.45095948700013)
(7.197509753181139, 2.3239212209403552, -22.229667985143006)
(7.659405992882302, 2.3895002385175688, -25.008376483285883)
(8.121302232583465, 2.4550792560947823, -27.78708498142876)
(8.583198472284629, 2.5206582736719954, -30.56579347957163)
(9.045094711985792, 2.586237291249209, -33.34450197771451)
(9.506990951686955, 2.6518163088264224, -36.123210475857384)
(9.968887191388118, 2.717395326403636, -38.90191897400026)
(10.430783431089282, 2.7829743439808494, -41.68062747214314)
(10.892679670790445, 2.8485533615580625, -44.45933597028601)
(11.354575910491608, 2.9141323791352756, -47.23804446842888)
(11.816472150192771, 2.97971139671248

In [149]:
a

[1.497123990844,
 1.346041446104676,
 1.1949589013653519,
 1.0438763566260278,
 0.8927938118867037,
 0.7417112671473796,
 0.5906287224080558,
 0.4395461776687315,
 0.28846363292940747,
 0.13738108819008366,
 -0.013701456549240598,
 -0.16478400128856463,
 -0.3158665460278889,
 -0.4669490907672129,
 -0.6180316355065365,
 -0.7691141802458605,
 -0.920196724985185,
 -1.0712792697245086,
 -1.222361814463833,
 -1.373444359203157,
 -1.5245269039424807,
 -1.6756094486818052,
 -1.8266919934211292,
 -1.9777745381604528,
 -2.1288570828997773,
 -2.2799396276391013,
 -2.4310221723784258,
 -2.5821047171177494]

In [148]:
z


[-5.557416996285752,
 -8.336125494428627,
 -11.114833992571503,
 -13.89354249071438,
 -16.672250988857254,
 -19.45095948700013,
 -22.229667985143006,
 -25.008376483285883,
 -27.78708498142876,
 -30.56579347957163,
 -33.34450197771451,
 -36.123210475857384,
 -38.90191897400026,
 -41.68062747214314,
 -44.45933597028601,
 -47.23804446842888,
 -50.016752966571765,
 -52.795461464714634,
 -55.57416996285752,
 -58.352878461000394,
 -61.13158695914326,
 -63.910295457286146,
 -66.68900395542902,
 -69.46771245357189,
 -72.24642095171477,
 -75.02512944985764,
 -77.80383794800052,
 -80.5825464461434]

In [260]:
len(a)

28

In [262]:
d,a,z = interpolate_point_sampling(30,center,DREP_L[0],if_L[2],0.1)

[3.50233984 1.79928908 0.        ] [ 16.89733079   3.70108059 -80.58254645]
yes
4.538941056699068 1.9304471154770748 -5.557416996285752
yes
4.679626097993681 1.996026133054288 -8.336125494428627
yes
4.679626097993681 2.0616051506315016 -11.114833992571503
yes
4.8446550576742515 2.127184168208715 -13.89354249071438
yes
4.8579131430326195 2.192763185785928 -16.672250988857254
yes
4.8579131430326195 2.2583422033631417 -19.45095948700013
yes
4.867775551460844 2.3239212209403552 -22.229667985143006
yes
4.917525496706888 2.3895002385175688 -25.008376483285883
yes
4.917525496706888 2.4550792560947823 -27.78708498142876
yes
4.917525496706888 2.5206582736719954 -30.56579347957163
yes
4.917525496706888 2.586237291249209 -33.34450197771451
yes
4.917525496706888 2.6518163088264224 -36.123210475857384
yes
4.917525496706888 2.717395326403636 -38.90191897400026
yes
4.917525496706888 2.7829743439808494 -41.68062747214314
yes
4.848709817864149 2.8485533615580625 -44.45933597028601
yes
4.848709817864149

In [138]:
cart2polTransform(DREP_L[0],center)

array([3.50233984, 1.79928908, 0.        ])

In [139]:
cart2polTransform(if_L[2],center)

array([ 16.89733079,  -2.58210472, -80.58254645])

In [ ]:
get_dwm(ai)

In [164]:
DREP_L[0]

array([-2.24930811, 52.77119827, -8.77660179])

In [163]:
if_L[2]

array([-15.77693822,  40.39159124, -89.35914824])

In [259]:
len(interp_list)

28

In [264]:
interp_list=[]
for di,ai,zi in zip(d,a,z):
    interp_list.append(cart2polTransform([di,ai,zi],origin = center, direction = 'pol2cart'))

In [251]:
d

[4.538941056699068,
 4.679626097993681,
 4.679626097993681,
 4.8446550576742515,
 4.8579131430326195,
 4.8579131430326195,
 4.867775551460844,
 4.917525496706888,
 4.917525496706888,
 4.917525496706888,
 4.917525496706888,
 4.917525496706888,
 4.917525496706888,
 4.917525496706888,
 4.848709817864149,
 4.848709817864149,
 4.737531924641851,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.7826987568478,
 4.759172449705568]

In [1]:
def get_dwm(angle):
    # Parameters:
    # angle : the radian angle of the interpolate points

    # Define the direction vector of the ray
    angle_rad = angle-
    direction = np.array([np.cos(angle_rad), np.sin(angle_rad), 0])

    # Define the length of the ray
    ray_length = 20

    # Calculate the end point of the ray
    end_raypoint = np.array(center) + ray_length * direction

    # Find the closest point on the slice to the rayend
    closest_point = sliced_mesh.find_closest_point(end_raypoint)
    
    # Calculate the distance
    d = np.sqrt(np.sum((center-sliced_mesh.points[closest_point])**2))
    
    return d



SyntaxError: invalid syntax (1254306139.py, line 6)

In [53]:
get_dwm(0.7853981633974483)

5.456247714282958

In [14]:
angle_rad = 0.7853981633974483
direction = np.array([np.cos(angle_rad), np.sin(angle_rad), 0])

# Define the length of the ray
ray_length = 20

# Calculate the end point of the ray
end_raypoint = np.array(center) + ray_length * direction

# Find the closest point on the slice to the rayend
closest_point = sliced_mesh.find_closest_point(interp1)

In [49]:
center-closest_point

array([-116.45599413,  -65.64011192, -123.77660179])

In [20]:
closest_point = sliced_mesh.find_closest_point(interp1)

In [21]:
# Create a Plotter and add the ray
#plotter = pv.Plotter()
plotter = BackgroundPlotter()
plotter.add_mesh(sliced_mesh, color = 'red')
plotter.add_mesh(line, color = 'red')
plotter.add_point_labels(interp1, ['interp1'], point_color = 'blue', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(DREP_L, list(DREP_L_Tbl['label']), font_size=24, point_color='green', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(center, ['O'], point_color = 'yellow', point_size=20, render_points_as_spheres=True, always_visible=True)
plotter.add_point_labels(sliced_mesh.points[closest_point], ['x'], point_color = 'blue', point_size=20, render_points_as_spheres=True, always_visible=True)
# Show the plotter
plotter.show()

In [135]:
etrp_pol = cart2polTransform(DREP_L[0])
endp_pol = cart2polTransform(if_L[0])

In [137]:
etrp_pol

array([52.81911353,  1.61339433, -8.77660179])

## DWMI计算：射线绘制

In [27]:
import pyvista as pv
import numpy as np

# Define the point and angle
point = center
angle_deg = 45  # Angle in degrees

# Convert angle to radians
angle_rad = np.radians(angle_deg)

# Define the direction vector of the ray
direction = np.array([np.cos(angle_rad), np.sin(angle_rad), 0])

# Define the length of the ray
ray_length = 10.0

# Calculate the end point of the ray
end_point = np.array(point) + ray_length * direction

# Create a line segment representing the ray
# ray = pv.Line(point, end_point)

# Create a Plotter and add the ray
plotter = pv.Plotter()
plotter.add_mesh(ray, color='red', line_width=2)

# Add any additional visualization elements or meshes to the plotter

# Show the plotter
plotter.show()


Widget(value="<iframe src='http://localhost:55463/index.html?ui=P_0x2084f7832e0_2&reconnect=auto' style='width…

In [28]:
angle_rad

0.7853981633974483

In [26]:
direction

[0.7071067811865476, 0.7071067811865476, 0]

## 坐标系转换

In [232]:
import math
def cart2polTransform(coordinate, origin = np.array([0,0,0]), direction='cart2pol'):
    ### Parameters:
    # coordinate: 3D array needs to transform
    # origin(deprecated): the origin of polar coordinate
    # direction: the direction of transform 'cart2pol','pol2cart'
    # 

    if direction == 'cart2pol':
        x = coordinate[0]-origin[0]
        y = coordinate[1]-origin[1]
        z = coordinate[2]-origin[2]
        pol = []
        pol.append((x**2+y**2)**0.5)
        a = math.atan2(y,x)
        pol.append(a if a>=0 else 2*math.pi+a)
        pol.append(z)
        return np.array(pol)
            
        
    elif direction == 'pol2cart':
        x = coordinate[0]
        y = coordinate[1]
        z = coordinate[2]
        cart = []
        cart.append(x*math.cos(y))
        cart.append(x*math.sin(y))
        cart.append(z)
        
        return np.array(cart)+origin
        
        
    else:
        raise Exception(" Wrong direction parameter input, should be 'cart2pol' or 'pol2cart'.")

        
        
    

In [233]:
a = cart2polTransform([-3,1,1],[0,0,0])

In [234]:
a

array([3.16227766, 2.8198421 , 1.        ])

In [127]:
b =  cart2polTransform([2,2,1],[1,1,1])

In [230]:
pol = []
a = -2

pol.append(a if a>0 else 2*math.pi+a)

In [231]:
pol

[4.283185307179586]

### 批量坐标转换

In [ ]:
import pyvista as pv
import numpy as np
from pyvista.utilities import vtk_to_numpy, numpy_to_vtk

# Create a PyVista PolyData object with Cartesian coordinate points
points = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
poly_data = pv.PolyData(points)

# Convert the Cartesian points to cylindrical coordinates 
cartesian_points = vtk_to_numpy(poly_data.points)
r = np.sqrt(cartesian_points[:, 0]**2 + cartesian_points[:, 1]**2)
theta = np.arctan2(cartesian_points[:, 1], cartesian_points[:, 0])
z = cartesian_points[:, 2]

# Convert the cylindrical coordinates back to a new PolyData object
cylindrical_points = np.column_stack((r, theta, z))
poly_data_cylindrical = pv.PolyData()
poly_data_cylindrical.points = numpy_to_vtk(cylindrical_points)

# Visualize the cylindrical coordinate points
plotter = pv.Plotter()
plotter.add_mesh(poly_data_cylindrical, color='red', point_size=10)
plotter.show()
